# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/onuragtas/Workspace/backup/backup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1220, 444)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backup = QtWidgets.QPushButton(Form)
        self.backup.setObjectName("backup")
        self.horizontalLayout.addWidget(self.backup)
        self.stop = QtWidgets.QPushButton(Form)
        self.stop.setEnabled(False)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.log = QtWidgets.QLabel(Form)
        self.log.setText("")
        self.log.setObjectName("log")
        self.verticalLayout_5.addWidget(self.log)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.server = QtWidgets.QLineEdit(Form)
        self.server.setObjectName("server")
        self.horizontalLayout_2.addWidget(self.server)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setObjectName("username")
        self.horizontalLayout_2.addWidget(self.username)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.connectButton = QtWidgets.QPushButton(Form)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rpath = QtWidgets.QLineEdit(Form)
        self.rpath.setObjectName("rpath")
        self.verticalLayout.addWidget(self.rpath)
        self.remoteList = QtWidgets.QListWidget(Form)
        self.remoteList.setObjectName("remoteList")
        self.verticalLayout.addWidget(self.remoteList)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lpath = QtWidgets.QLineEdit(Form)
        self.lpath.setObjectName("lpath")
        self.verticalLayout_3.addWidget(self.lpath)
        self.localList = QtWidgets.QListWidget(Form)
        self.localList.setObjectName("localList")
        self.verticalLayout_3.addWidget(self.localList)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.servers = QtWidgets.QComboBox(Form)
        self.servers.setObjectName("servers")
        self.gridLayout_2.addWidget(self.servers, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Backup"))
        self.backup.setText(_translate("Form", "Backup"))
        self.stop.setText(_translate("Form", "Stop"))
        self.label.setText(_translate("Form", "Sunucu:"))
        self.server.setText(_translate("Form", "server.resoft.org"))
        self.label_2.setText(_translate("Form", "Kullanıcı Adı:"))
        self.username.setText(_translate("Form", "admin"))
        self.label_3.setText(_translate("Form", "Şifre:"))
        self.password.setText(_translate("Form", "onuragtas100"))
        self.connectButton.setText(_translate("Form", "Bağlan"))

